creator: dennyrwa
lang: id
locale: id_ID
title: Sewa Mobil Tulungagung | Tulungagung Trans
company: Tulungagung Trans
description: Hubungi / WA ke 0813-3666-5654 dan dapatkan Rental, Carter dan Sewa Mobil Murah di Tulungagung. Kami melayani jasa sewa mobil Tulungagung dan luar kota.
keywords: sewa mobil tulungagung, rental mobil tulungagung, carter mobil tulungagung, 
section-1: Sewa Mobil Tulungagung
section-1-a: Tulungagung Trans
section-1-b: melayani Rental Mobil Tulungagung, Sewa Mobil di Tulungagung dan Paket Wisata
section-2: Tentang Kami
section-2-a: Tulungagung Trans adalah sebuah Perusahaan Mobil yang berkantor di Tulungagung, Jawa Timur. Kami melayani berbagai macam paket tour seperti ke Bali, Jogja, Malang, Batu, Banyuwangi, Bandung, Lombok, droping antar kota serta antar jemput juanda dll. Baik itu untuk perorangan, sekolah, perusahaan ataupun instansi. Selain itu kami juga melayani carter mobil + sopir di Tulungagung yang berkualitas dengan tarif yang terjangkau dengan pelayanan terbaik. Kami siap melayani kebutuhan transportasi anda seperti sewa mobil untuk wisata, keperluan bisnis, wisuda mahasiswa, pindahan, pernikahan, mudik lebaran, event, perusahaan dan berbagai keperluan anda lainnya. Jika anda memiliki pertanyaan tentang layanan kami silahkan menghubungi kami melalui telepon, sms, WA ataupun email kami. Terimakasih dan selamat menikmati layanan dari kami.
section-3: Cara Pemesanan
section-3-a: Hubungi Kami
section-3-a-des: Telepon atau WA kami segera dan tentukan kendaraan yang anda inginkan.
section-3-b: Tentukan Jadwal
section-3-b-des: Segera tentukan jadwal anda setelah Mobil yang ada inginkan tersedia.
section-3-c: Bayar Uang Muka
section-3-c-des: Lakukan pembayaran uang muka sebagai tanda jadi.
section-3-d: Kami akan jemput
section-3-d-des: Kami akan jemput anda pada tanggal yang telah ditentukan.
section-4: Tunggu Apalagi
section-4-a: Jangan ragu segera konsultasikan keinginan Anda
section-4-b: Hubungi Kami
section-5: Harga Sewa
section-6: Frequently Asked Questions
section-7: Paket Wisata
section-8: Gallery
logo-2: /img/logo-tulungagung-trans.png
visi-1: Tulungagung Trans adalah sebuah Perusahaan Tour & Carter Mobil yang berkantor di Tulungagung, Jawa Timur.
visi-2: Jika anda memiliki pertanyaan tentang layanan kami silahkan menghubungi kami melalui telepon, sms, WA ataupun email kami.
twitter: 
instagram: https://www.instagram.com/rental_mobil_tulungagung/
facebook: https://www.facebook.com/tulungagungtrans/
google-plus: 
copyright: © Copyright <strong>Tulungagung Trans</strong>. All Rights Reserved and All the trademarks are the property of their respective owners
whatsapp-float-desktop: https://web.whatsapp.com/send?phone=6281336665654&text=Hallo, saya mau sewa mobil
whatsapp-float-phone: whatsapp://send?text=Hallo, saya mau sewa mobil!&phone=+6281336665654
exclude: [README.md]
email: nobitalazi889@gmail.com
type: AutoRental
streetAddress: Jl. Raya Pulosari No. 1
address:  Dsn. Demangan, Desa Bendiljati Wetan, Kec. Sumbergempol, Kab. Tulungagung, Jawa Timur, Indonesia
postalCode: 66291
telephone: +6281336665654
telephonedetail: 0813-3666-5654
fb_app_id: 267068847343048
google-my-bussiness: https://maps.app.goo.gl/KntUZeNRE9SRkvUy9
whatsapp-api: https://api.whatsapp.com/send?text=Hallo%20Tulungagung%20Trans%20&%20(Name)%20(Address)%20&phone=6281336665654
favicon: /favicon.ico
siteurl: https://sewamobiltulungagung.com
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-feed
collections:
  data-slider:
    output: true
  data-paket-wisata:
    output: true
    permalink: /data-paket-wisata/:name
  data-products:
    output: true
  data-faq:
    output: true
  data-gallery:
    output: true
  data-instagram:
    output: true